/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.xmlportletfactory.portal.example01.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PortletOne service. Represents a row in the &quot;portletone_PortletOne&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.xmlportletfactory.portal.example01.model.impl.PortletOneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.xmlportletfactory.portal.example01.model.impl.PortletOneImpl}.
 * </p>
 *
 * @author Jack A. Rider
 * @see PortletOne
 * @see org.xmlportletfactory.portal.example01.model.impl.PortletOneImpl
 * @see org.xmlportletfactory.portal.example01.model.impl.PortletOneModelImpl
 * @generated
 */
public interface PortletOneModel extends BaseModel<PortletOne> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a portlet one model instance should use the {@link PortletOne} interface instead.
	 */

	/**
	 * Returns the primary key of this portlet one.
	 *
	 * @return the primary key of this portlet one
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this portlet one.
	 *
	 * @param primaryKey the primary key of this portlet one
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the portlet one ID of this portlet one.
	 *
	 * @return the portlet one ID of this portlet one
	 */
	public long getPortletOneId();

	/**
	 * Sets the portlet one ID of this portlet one.
	 *
	 * @param PortletOneId the portlet one ID of this portlet one
	 */
	public void setPortletOneId(long PortletOneId);

	/**
	 * Returns the company ID of this portlet one.
	 *
	 * @return the company ID of this portlet one
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this portlet one.
	 *
	 * @param companyId the company ID of this portlet one
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this portlet one.
	 *
	 * @return the group ID of this portlet one
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this portlet one.
	 *
	 * @param groupId the group ID of this portlet one
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this portlet one.
	 *
	 * @return the user ID of this portlet one
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this portlet one.
	 *
	 * @param userId the user ID of this portlet one
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this portlet one.
	 *
	 * @return the user uuid of this portlet one
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this portlet one.
	 *
	 * @param userUuid the user uuid of this portlet one
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the portlet one description of this portlet one.
	 *
	 * @return the portlet one description of this portlet one
	 */
	@AutoEscape
	public String getPortletOneDescription();

	/**
	 * Sets the portlet one description of this portlet one.
	 *
	 * @param PortletOneDescription the portlet one description of this portlet one
	 */
	public void setPortletOneDescription(String PortletOneDescription);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(PortletOne portletOne);

	public int hashCode();

	public CacheModel<PortletOne> toCacheModel();

	public PortletOne toEscapedModel();

	public String toString();

	public String toXmlString();
}