/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fl.uploadfile.service.base;

import com.fl.uploadfile.model.UploadFile;
import com.fl.uploadfile.service.UploadFileLocalService;
import com.fl.uploadfile.service.persistence.UploadFilePersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the upload file local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.fl.uploadfile.service.impl.UploadFileLocalServiceImpl}.
 * </p>
 *
 * @author Manisha
 * @see com.fl.uploadfile.service.impl.UploadFileLocalServiceImpl
 * @see com.fl.uploadfile.service.UploadFileLocalServiceUtil
 * @generated
 */
public abstract class UploadFileLocalServiceBaseImpl
	implements UploadFileLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.fl.uploadfile.service.UploadFileLocalServiceUtil} to access the upload file local service.
	 */

	/**
	 * Adds the upload file to the database. Also notifies the appropriate model listeners.
	 *
	 * @param uploadFile the upload file
	 * @return the upload file that was added
	 * @throws SystemException if a system exception occurred
	 */
	public UploadFile addUploadFile(UploadFile uploadFile)
		throws SystemException {
		uploadFile.setNew(true);

		uploadFile = uploadFilePersistence.update(uploadFile, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(uploadFile);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return uploadFile;
	}

	/**
	 * Creates a new upload file with the primary key. Does not add the upload file to the database.
	 *
	 * @param fileUploadId the primary key for the new upload file
	 * @return the new upload file
	 */
	public UploadFile createUploadFile(long fileUploadId) {
		return uploadFilePersistence.create(fileUploadId);
	}

	/**
	 * Deletes the upload file with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param fileUploadId the primary key of the upload file
	 * @throws PortalException if a upload file with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteUploadFile(long fileUploadId)
		throws PortalException, SystemException {
		UploadFile uploadFile = uploadFilePersistence.remove(fileUploadId);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(uploadFile);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the upload file from the database. Also notifies the appropriate model listeners.
	 *
	 * @param uploadFile the upload file
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteUploadFile(UploadFile uploadFile)
		throws SystemException {
		uploadFilePersistence.remove(uploadFile);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(uploadFile);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return uploadFilePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return uploadFilePersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return uploadFilePersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return uploadFilePersistence.countWithDynamicQuery(dynamicQuery);
	}

	public UploadFile fetchUploadFile(long fileUploadId)
		throws SystemException {
		return uploadFilePersistence.fetchByPrimaryKey(fileUploadId);
	}

	/**
	 * Returns the upload file with the primary key.
	 *
	 * @param fileUploadId the primary key of the upload file
	 * @return the upload file
	 * @throws PortalException if a upload file with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public UploadFile getUploadFile(long fileUploadId)
		throws PortalException, SystemException {
		return uploadFilePersistence.findByPrimaryKey(fileUploadId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return uploadFilePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the upload files.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of upload files
	 * @param end the upper bound of the range of upload files (not inclusive)
	 * @return the range of upload files
	 * @throws SystemException if a system exception occurred
	 */
	public List<UploadFile> getUploadFiles(int start, int end)
		throws SystemException {
		return uploadFilePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of upload files.
	 *
	 * @return the number of upload files
	 * @throws SystemException if a system exception occurred
	 */
	public int getUploadFilesCount() throws SystemException {
		return uploadFilePersistence.countAll();
	}

	/**
	 * Updates the upload file in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param uploadFile the upload file
	 * @return the upload file that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public UploadFile updateUploadFile(UploadFile uploadFile)
		throws SystemException {
		return updateUploadFile(uploadFile, true);
	}

	/**
	 * Updates the upload file in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param uploadFile the upload file
	 * @param merge whether to merge the upload file with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the upload file that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public UploadFile updateUploadFile(UploadFile uploadFile, boolean merge)
		throws SystemException {
		uploadFile.setNew(false);

		uploadFile = uploadFilePersistence.update(uploadFile, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(uploadFile);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return uploadFile;
	}

	/**
	 * Returns the upload file local service.
	 *
	 * @return the upload file local service
	 */
	public UploadFileLocalService getUploadFileLocalService() {
		return uploadFileLocalService;
	}

	/**
	 * Sets the upload file local service.
	 *
	 * @param uploadFileLocalService the upload file local service
	 */
	public void setUploadFileLocalService(
		UploadFileLocalService uploadFileLocalService) {
		this.uploadFileLocalService = uploadFileLocalService;
	}

	/**
	 * Returns the upload file persistence.
	 *
	 * @return the upload file persistence
	 */
	public UploadFilePersistence getUploadFilePersistence() {
		return uploadFilePersistence;
	}

	/**
	 * Sets the upload file persistence.
	 *
	 * @param uploadFilePersistence the upload file persistence
	 */
	public void setUploadFilePersistence(
		UploadFilePersistence uploadFilePersistence) {
		this.uploadFilePersistence = uploadFilePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.fl.uploadfile.model.UploadFile",
			uploadFileLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.fl.uploadfile.model.UploadFile");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return UploadFile.class;
	}

	protected String getModelClassName() {
		return UploadFile.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = uploadFilePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = UploadFileLocalService.class)
	protected UploadFileLocalService uploadFileLocalService;
	@BeanReference(type = UploadFilePersistence.class)
	protected UploadFilePersistence uploadFilePersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private static Log _log = LogFactoryUtil.getLog(UploadFileLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}